apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aks-watcher-backend-data
  namespace: aks-watcher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
